### ISSUE TITLE
Preserve manual empty lines

### ISSUE THREAD

**Issue by thetutlage** [sajansharmanz/prettier-plugin-edgejs#1]
When using the extension, I see that it removes all the empty lines from the Edge templates. It will be nice if we have the behavior similar to how Prettier works with JavaScript files. i.e `Manual empty lines are preserved (maximum 1)`. Also, if there are more than one empty lines, then they must collapse to one empty line.

## Current behavior

https://github.com/sajansharmanz/prettier-plugin-edgejs/assets/1706381/d98e20f2-0519-4653-a252-a55b6b23597d

**Comment by sajansharmanz** [comment]
Hey,

Yes this is on the to do list already.

I'll try make some time to look into it soon, just super busy with life at the moment.

I'll keep you updated

**Comment by thetutlage** [comment]
Sure. Not in hurry. I just wanted to track all the issues that I encounter and see if I can also find time to fix some of them.

I have found a couple of issues with SVGs too. Will submit them as well :)

**Comment by sajansharmanz** [comment]
Enhancement released as part of `prettier-edgejs@0.2.14`

Please let me know if you encounter any issues
